### ISSUE TITLE
Invalid schema

### ISSUE THREAD

**Issue by fabiojansenbr** [sugarkubes/generators#1]
Im trying to use the generator using the schema from the readme but im getting "invalid schema error".

sugar-generate --type api --name monkey --schema D:\Demos\generator\monkey.json --destination D:\Demos\generator\

schema:

`{
  "schema": {
    "name": {
      "type": "String",
      "default": ""
    },
    "isDead": {
      "type": "Boolean",
      "default": false
    },
    "age": {
      "type": "Number",
      "default": false
    }
  },
  "statics": {}
}`

Tryied with the schema on same folder. The error is the same.

**Comment by wrannaman** [comment]
let me take a look!

**Comment by paulovlobato** [comment]
By some reason, the sugar-generate is looking for the schema (monkey.json file) inside the folder "/usr/local/lib/node_modules" + parsed argument as the file location.

**Comment by wrannaman** [comment]
ah that would explain it.

**Comment by wrannaman** [comment]
I accidently have the graphql api generator merged already with the master branch locally so im going to fix both these issues and push the graphql generator as well. should be today.

**Comment by paulovlobato** [comment]
Thanks, we're looking forward to it!

**Comment by wrannaman** [comment]
@paulovlobato @fabiojansenbr I've updated **sugar-generate** to version 0.0.14. It will also now generate graphql endpoints :) Let me know if this latest release solves both your issues and I'll close it. Thanks for reaching out! 

Also lmk what other features you think would be cool


<img width="591" alt="Screen Shot 2019-06-06 at 12 40 48 PM" src="https://user-images.githubusercontent.com/5325165/59061511-8caa9580-8858-11e9-80f0-d2bf1975ca87.png">
<img width="534" alt="Screen Shot 2019-06-06 at 12 40 21 PM" src="https://user-images.githubusercontent.com/5325165/59061512-8caa9580-8858-11e9-9f20-aeb843ae9ace.png">
<img width="662" alt="Screen Shot 2019-06-06 at 12 40 10 PM" src="https://user-images.githubusercontent.com/5325165/59061513-8caa9580-8858-11e9-98f4-0fbb72d32744.png">

**Comment by paulovlobato** [comment]
It solved, but now I'm facing several "mongo connection failed". Not sure if it's related to the latest fix. Something with mocha, I'd say...

**Comment by wrannaman** [comment]
@paulovlobato in the configs/config.json file is the mongodb connection url. Sounds like that connection string is wrong. 

- Do you have mongo running on localhost (or better 0.0.0.0) using ```sudo mongod --bind_all```?

**Comment by paulovlobato** [comment]
Yep, can confirm the mongod service was the issue. Restart it did the trick. Thanks!
