### ISSUE TITLE
swagger-inline not automatically called

### ISSUE THREAD

**Issue by paulovlobato** [sugarkubes/generators#3]
The `swagger-inline` is not being called automatically, so when the environment is running, no `swagger.json` file is located when browsing the web app.

The following line: `swagger-inline './controller/*/*.js' './models/*.js' --base './swaggerBase.yaml' --out swagger.json` has to be manually called from within the generated api folder.

**Comment by wrannaman** [comment]
Good point. I can add this to the start script.

**Comment by wrannaman** [comment]
There is one for the docs, you can do ```npm run docs``. but I'll put it in the start script as well for convenience.

**Comment by wrannaman** [comment]
closed with new version 0.1.0. @paulovlobato should generate docs now with both ```npm run start``` and ```npm run docs```
