### ISSUE TITLE
invalid schema example

### ISSUE THREAD

**Issue by Reeko94** [sugarkubes/generators#7]
When i launch sugar-generate  -s monkey.json with this monkey.json 

{
  "schema": {
    "name": { "type": "String", "default": "" },
    "isDead": { "type": "Boolean", "default": false },
    "age": { "type": "Number", "default": false }
  },
  "statics": {}
}

My terminal return 
Error => invalid schema. Schema requires a name

Is it normal ?

**Comment by wrannaman** [comment]
Let me update the documentation for you

**Comment by wrannaman** [comment]
```json
{
  "name": "monkey",
  "schema": {
    "name": {
      "type": "String",
      "default": ""
    },
    "alive": {
      "type": "Boolean",
      "default": false
    },
    "age": {
      "type": "Number",
      "default": false
    }
  }
}
```

just needs a name property and you should be good! lmk if that fixes it for you
